server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.46.247:3306/my_blog_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: abc123!

  jpa:
    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password:
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 5

  main:
    allow-bean-definition-overriding: true

shiro:
  session:
    expire: 2592000 #30天